# Site settings
title: Ryan Toole - Personal Site
email: rtoole13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A space to showcase a few projects.
baseurl:  '' # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
repository: https://github.com/rtoole13/rtoole13.github.io
twitter_username: RyanBri04146241
github_username:  rtoole13

# Build settings
markdown: kramdown

highlighter: rouge

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:path/


